services:
    napcat:
        environment:
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        ports:
            - 3001:3001
            - 6099:6099
        container_name: napcat
        network_mode: bridge
        restart: always
        image: napcat:1.0
        volumes:
          - ./data/QQ:/app/.config/QQ
          - ./data/napcat:/app/napcat/config
